version: '3.9'

services:
  db:
    image: postgres:15
    container_name: clasesManagementContainer
    environment:
      POSTGRES_USER: renardi
      POSTGRES_PASSWORD: test
      POSTGRES_DB: clasesManagement
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: