version: '3.9'

services:
  db:
    image: postgres:15
    container_name: clasesManagementContainer
    environment:
      POSTGRES_USER: renardi
      POSTGRES_PASSWORD: test
      POSTGRES_DB: clasesManagement
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


web:
    build:
      context: ../.
      dockerfile: ./Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        pip install -r requirements.txt
        python manage.py runserver 0.0.0.0:8000
        gunicorn --bind 0.0.0.0:8000 classmanagement.wsgi:application --reload
    volumes:
      - ../:/clasesManagement
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: